language: cpp

compiler:
- gcc

sudo: required

#rvm:
#- gcc_4.9
#- gcc_5.2
#- python_plot
#- gnuplot

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"

# Boost installation
- wget -q http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
- mv download boost.tar.gz
- tar -xf boost.tar.gz
- cd boost_1_59_0
- sudo ./bootstrap.sh
- sudo ./b2 -d1 install
- cd ..


# Anaconda installation
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=3.5 anaconda
- source activate test-environment

# Build KAT
- ./autogen.sh


