language: cpp

compiler:
- gcc

sudo: required

before_install:
- add-apt-repository -y ppa:ubuntu-toolchain-r/test
- apt-get update -qq
- apt-get install libboost-all-dev
- ./autogen.sh 

install:
- apt-get install -qq g++-4.9
- export CXX="g++-4.9"

