language: cpp

compiler:
- gcc

sudo: required

#rvm:
#- gcc_4.9
#- gcc_5.2
#- python_plot
#- gnuplot

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"
#- wget -q http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
#- mv download boost.tar.gz
#- tar -xf boost.tar.gz
#- cd boost_1_59_0
#- sudo ./bootstrap.sh
#- sudo ./b2 -d1 install
#- cd ..
- wget -q https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda3-2.4.0-Linux-x86_64.sh
- sudo bash ./Anaconda3-2.4.0-Linux-x86_64.sh -b -p /usr/local/share/anaconda3
- export PATH="/usr/local/share/anaconda3/bin:$PATH"
- python3 -c "from distutils.sysconfig import *; print(get_config_var('CONFINCLUDEPY'))"
- ldd python3
- ./autogen.sh 

