language: cpp

compiler:
- clang
- gcc

sudo: false

before_install:
- add-apt-repository -y ppa:ubuntu-toolchain-r/test
- apt-get update -qq
- ./autogen.sh 

install:
- apt-get install -qq g++-4.9
- export CXX="g++-4.9"

