language: cpp

matrix:
    include:
            - os: linux
              sudo: required
              compiler: gcc
              env: PYTHON=NO
            - os: linux
              sudo: required
              compiler: gcc
              env: COMPILER=GCC5 PYTHON=YES
            - os: linux
              sudo: required
              compiler: gcc
              env: COMPILER=GCC6 PYTHON=YES
            - os: linux
              sudo: required
              compiler: gcc
              env: COMPILER=GCC7 PYTHON=YES
            - os: osx
              compiler: clang
              env: PYTHON=YES

# safelist
branches:
  only:
  - master
  - develop


# Install dependencies: compilers, autotools, python
install:
- ./.travis/install.sh

# Build boost: comes with KAT but has a non-autotools build system so must be created separately
- ./build_boost.sh

# Generate KAT and Jellyfish configration scripts
- ./autogen.sh

# Make sure python's available at runtime (if necessary) and then build KAT and run tests
script:
- if [[ "$PYTHON" == "YES" ]]; then 
    export PATH="$HOME/miniconda/bin:$PATH" && source activate test-environment && ./configure --with-sse;
  else
    ./configure --with-sse --disable-pykat;
  fi
- make V=1
- make V=1 check
