language: cpp

compiler:
- gcc

sudo: required

#rvm:
#- gcc_4.9
#- gcc_5.2
#- python_plot
#- gnuplot

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"
- sudo apt-get install libboost-system-dev
- sudo apt-get install libboost-filesystem-dev
- sudo apt-get install libboost-program-options-dev
- sudo apt-get install libboost-chrono-dev
- sudo apt-get install libboost-timer-dev
- sudo apt-get install libboost-test-dev
- wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda3-2.4.0-Linux-x86_64.sh
- bash ~/Anaconda3-2.4.0-Linux-x86_64.sh -b -p $HOME/anaconda3
export PATH="$HOME/anaconda3/bin:$PATH"
- ./autogen.sh 

