language: cpp

git:
  submodules: false

matrix:
    include:
            - os: linux
              sudo: required
              compiler: gcc
              env: PLOT=none
            - os: linux
              sudo: required
              compiler: gcc
              env: COMPILER=GCC5 PLOT=python
            - os: osx
              compiler: clang

# safelist
branches:
  only:
  - master
  - develop

# Setup compiler
before_install:
- ./.travis/before_install.sh

# Install dependencies: python
install:
- ./.travis/install.sh

# Build boost
- ./build_boost.sh

# Build KAT
- ./autogen.sh

# Make sure python's available at runtime (if necessary) and then build KAT and run tests
script:
- if [[ "$COMPILER" == "GCC5" ]]; then export CXX="g++-5" && export CC="gcc-5"; elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.9" && export CC="gcc-4.9"; fi
- if [[ "$PLOT" == "python" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="$HOME/miniconda/bin:$PATH" && source activate test-environment; fi
- gcc --version
- g++ --version
- if [[ "$PLOT" == "python" ]]; then ./configure; else ./configure --disable-pykat; fi
- make V=1
- make V=1 check
