language: cpp

matrix:
    include:
            - os: linux
              sudo: required
              compiler: gcc
              env: PLOT=none
            - os: linux
              sudo: required
              compiler: gcc
              env: PLOT=python
            - os: linux
              sudo: required
              env: PLOT=gnuplot
            - os: linux
              sudo: required
              compiler: gcc
              env: COMPILER=GCC5 PLOT=python
            - os: osx
              compiler: clang
            
# Setup compiler
before_install:
- ./.travis/before_install.sh

# Install dependencies: (Boost and python, and setup KAT)
install:
- ./.travis/install.sh

# Build KAT
- ./autogen.sh

# Make sure python's available at runtime (if necessary) and then build KAT and run tests
script:
- if [[ "$PLOT" == "python" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib:$LD_LIBRARY_PATH; fi

- ./configure --disable-silent-rules && make && make check && make distcheck

