language: cpp

compiler:
- gcc

sudo: required

env:
- PLOT=none
- PLOT=python
- PLOT=gnuplot
- COMPILER=GCC5

# Setup compiler
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- if ["$COMPILER" == "GCC5" ]; then sudo apt-get install -qq g++-5 && export CXX="g++-5" && export CC="gcc-5";  else sudo apt-get install -qq g++-4.9 && export CXX="g++-4.9" && export CC="gcc-4.9"; fi
- gcc --version

# Install dependencies: (Boost and python, and setup KAT)
install:

# Boost installation
- wget -q http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
- mv download boost.tar.gz
- tar -xf boost.tar.gz
- cd boost_1_59_0
- sudo ./bootstrap.sh --with-libraries=chrono,timer,program_options,filesystem,system
- sudo ./b2 -d0 --toolset=gcc-4.9 install
- cd ..


# Plotting installation
- if [ "$PLOT" == "python" ]; then ./.travis.install-anaconda.sh; source activate test-environment; elif [ "$PLOT" == "gnuplot" ]; then sudo apt-get install gnuplot; fi


# Build KAT
- ./autogen.sh

# Make sure python's available at runtime and then build KAT and run tests
script:
- export LD_LIBRARY_PATH=/home/travis/miniconda/envs/test-environment/lib:%LD_LIBRARY_PATH
- ./configure --disable-silent-rules && make && make check && make distcheck

